-- ============================================================================
-- 0045 ROLLBACK — restore the vendor-look DB rows purged by 0045_purge_vendor_looks.
--
-- WHY THIS EXISTS: 0041_template_catalog_import.sql restores ONLY `haircut` among the
-- six vendor-look rows that lived in `templates`. The other five (alotan, barberx,
-- barberz, feane, restoran) were seeded OUT-OF-BAND (the generator
-- 4-Dokument-Underlag/03-template-katalog/templates-import.sql is gone) and captured in
-- NO migration → re-applying 0041 would NOT bring them back. This file is a VERBATIM
-- snapshot of the live rows (templates + template_slots) taken immediately before the
-- purge, so goal-51 is truly reversible (rollback contract).
--
-- Idempotent (on conflict do nothing). Order: templates THEN template_slots (FK).
-- Also restores test234rf's settings.look pin. Re-run = no-op.
-- ============================================================================
begin;

-- ===== templates (6) =====
insert into templates (key,name,tags,tokens,sections,status) values ('alotan','Corevo Alotan','{"typ": "storefront", "stil": "warm", "scope": "booking", "licens": "kräver-kredit", "bransch": "frisör"}','{"font": {"body": "Roboto", "heading": "Poppins"}, "color": {"bg": null, "text": "#111111", "muted": null, "accent": "#ff6d24", "primary": "#ff6d24", "surface": null, "secondary": "#1d1d1d"}, "layout": {"max_width": null, "nav_position": "sticky", "border_radius": null}}','["hero", "services", "team", "testimonials", "footer"]','active') on conflict (key) do nothing;
insert into templates (key,name,tags,tokens,sections,status) values ('barberx','Corevo BarberX','{"typ": "storefront", "stil": "dark", "scope": "booking", "licens": "kräver-kredit", "bransch": "frisör"}','{"font": {"body": "Roboto", "heading": "Oswald"}, "color": {"bg": null, "text": "#111111", "muted": null, "accent": "#c79a5a", "primary": "#c79a5a", "surface": null, "secondary": "#111111"}, "layout": {"max_width": null, "nav_position": "sticky", "border_radius": null}}','["hero", "services", "team", "testimonials", "footer"]','active') on conflict (key) do nothing;
insert into templates (key,name,tags,tokens,sections,status) values ('barberz','Corevo Barberz','{"typ": "storefront", "stil": "dark", "scope": "booking", "licens": "kräver-kredit", "bransch": "barbershop"}','{"font": {"body": "Roboto", "heading": "Oswald"}, "color": {"bg": null, "text": "#111111", "muted": null, "accent": "#d4a056", "primary": "#d4a056", "surface": null, "secondary": "#161616"}, "layout": {"max_width": null, "nav_position": "sticky", "border_radius": null}}','["hero", "services", "team", "testimonials", "footer"]','active') on conflict (key) do nothing;
insert into templates (key,name,tags,tokens,sections,status) values ('feane','Corevo Feane','{"typ": "storefront", "stil": "bold", "scope": "booking", "licens": "kräver-kredit", "bransch": "restaurang"}','{"font": {"body": "Poppins", "heading": "Poppins"}, "color": {"bg": null, "text": "#111111", "muted": null, "accent": "#ffbe33", "primary": "#ffbe33", "surface": null, "secondary": "#222831"}, "layout": {"max_width": null, "nav_position": "sticky", "border_radius": null}}','["hero", "menu", "gallery", "testimonials", "contact", "footer"]','active') on conflict (key) do nothing;
insert into templates (key,name,tags,tokens,sections,status) values ('haircut','Corevo Haircut','{"typ": "storefront", "stil": "bold", "scope": "booking", "licens": "kräver-kredit", "bransch": "frisör"}','{"font": {"body": "Oswald", "heading": "Roboto"}, "color": {"bg": null, "text": "#111111", "muted": null, "accent": "#191c24", "primary": "#eb1616", "surface": null, "secondary": "#191c24"}, "layout": {"max_width": null, "nav_position": "sticky", "border_radius": null}}','["hero", "services", "team", "testimonials", "footer"]','active') on conflict (key) do nothing;
insert into templates (key,name,tags,tokens,sections,status) values ('restoran','Corevo Restoran','{"typ": "storefront", "stil": "warm", "scope": "booking", "licens": "kräver-kredit", "bransch": "restaurang"}','{"font": {"body": "Roboto", "heading": "Playfair Display"}, "color": {"bg": null, "text": "#111111", "muted": null, "accent": "#fea116", "primary": "#fea116", "surface": null, "secondary": "#0f172a"}, "layout": {"max_width": null, "nav_position": "sticky", "border_radius": null}}','["hero", "menu", "gallery", "testimonials", "contact", "footer"]','active') on conflict (key) do nothing;

-- ===== template_slots (80) =====
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('alotan','hero','hero.bg','Hero – bakgrundsbild','asset','image','16:9',NULL,NULL,'f',0,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('alotan','hero','hero.heading','Hero – rubrik','text',NULL,NULL,NULL,NULL,'f',1,'text','Välkommen',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('alotan','hero','hero.subheading','Hero – underrubrik','text',NULL,NULL,NULL,NULL,'f',2,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('alotan','services','services.heading','Tjänster – rubrik','text',NULL,NULL,NULL,NULL,'f',100,'text','Våra tjänster',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('alotan','services','services.list','Tjänster – tjänstelista (boknings-modul)','module',NULL,NULL,'booking','service_list','f',101,NULL,NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('alotan','team','team.heading','Team – rubrik','text',NULL,NULL,NULL,NULL,'f',200,'text','Vårt team',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('alotan','team','team.member.{i}.photo','Medarbetare – bild','asset','image','1:1',NULL,NULL,'t',201,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('alotan','team','team.member.{i}.name','Medarbetare – namn','text',NULL,NULL,NULL,NULL,'t',202,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('alotan','team','team.member.{i}.role','Medarbetare – titel','text',NULL,NULL,NULL,NULL,'t',203,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('alotan','testimonials','testimonials.heading','Omdömen – rubrik','text',NULL,NULL,NULL,NULL,'f',300,'text','Vad våra kunder säger',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('alotan','footer','footer.logo','Sidfot – logotyp','asset','logo',NULL,NULL,NULL,'f',500,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('alotan','footer','footer.text','Sidfot – text','text',NULL,NULL,NULL,NULL,'f',501,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberx','hero','hero.bg','Hero – bakgrundsbild','asset','image','16:9',NULL,NULL,'f',0,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberx','hero','hero.heading','Hero – rubrik','text',NULL,NULL,NULL,NULL,'f',1,'text','Välkommen',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberx','hero','hero.subheading','Hero – underrubrik','text',NULL,NULL,NULL,NULL,'f',2,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberx','services','services.heading','Tjänster – rubrik','text',NULL,NULL,NULL,NULL,'f',100,'text','Våra tjänster',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberx','services','services.list','Tjänster – tjänstelista (boknings-modul)','module',NULL,NULL,'booking','service_list','f',101,NULL,NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberx','team','team.heading','Team – rubrik','text',NULL,NULL,NULL,NULL,'f',200,'text','Vårt team',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberx','team','team.member.{i}.photo','Medarbetare – bild','asset','image','1:1',NULL,NULL,'t',201,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberx','team','team.member.{i}.name','Medarbetare – namn','text',NULL,NULL,NULL,NULL,'t',202,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberx','team','team.member.{i}.role','Medarbetare – titel','text',NULL,NULL,NULL,NULL,'t',203,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberx','testimonials','testimonials.heading','Omdömen – rubrik','text',NULL,NULL,NULL,NULL,'f',300,'text','Vad våra kunder säger',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberx','footer','footer.logo','Sidfot – logotyp','asset','logo',NULL,NULL,NULL,'f',500,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberx','footer','footer.text','Sidfot – text','text',NULL,NULL,NULL,NULL,'f',501,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberz','hero','hero.bg','Hero – bakgrundsbild','asset','image','16:9',NULL,NULL,'f',0,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberz','hero','hero.heading','Hero – rubrik','text',NULL,NULL,NULL,NULL,'f',1,'text','Välkommen',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberz','hero','hero.subheading','Hero – underrubrik','text',NULL,NULL,NULL,NULL,'f',2,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberz','services','services.heading','Tjänster – rubrik','text',NULL,NULL,NULL,NULL,'f',100,'text','Våra tjänster',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberz','services','services.item.{i}.icon','Tjänst – ikon/bild','asset','image','1:1',NULL,NULL,'t',101,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberz','services','services.item.{i}.title','Tjänst – titel','text',NULL,NULL,NULL,NULL,'t',102,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberz','services','services.item.{i}.text','Tjänst – beskrivning','text',NULL,NULL,NULL,NULL,'t',103,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberz','team','team.heading','Team – rubrik','text',NULL,NULL,NULL,NULL,'f',200,'text','Vårt team',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberz','team','team.member.{i}.photo','Medarbetare – bild','asset','image','1:1',NULL,NULL,'t',201,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberz','team','team.member.{i}.name','Medarbetare – namn','text',NULL,NULL,NULL,NULL,'t',202,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberz','team','team.member.{i}.role','Medarbetare – titel','text',NULL,NULL,NULL,NULL,'t',203,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberz','testimonials','testimonials.heading','Omdömen – rubrik','text',NULL,NULL,NULL,NULL,'f',300,'text','Vad våra kunder säger',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberz','footer','footer.logo','Sidfot – logotyp','asset','logo',NULL,NULL,NULL,'f',500,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('barberz','footer','footer.text','Sidfot – text','text',NULL,NULL,NULL,NULL,'f',501,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('feane','hero','hero.bg','Hero – bakgrundsbild','asset','image','16:9',NULL,NULL,'f',0,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('feane','hero','hero.heading','Hero – rubrik','text',NULL,NULL,NULL,NULL,'f',1,'text','Välkommen',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('feane','hero','hero.subheading','Hero – underrubrik','text',NULL,NULL,NULL,NULL,'f',2,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('feane','menu','menu.heading','Meny – rubrik','text',NULL,NULL,NULL,NULL,'f',120,'text','Meny',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('feane','menu','menu.item.{i}.image','Menyrätt – bild','asset','image','1:1',NULL,NULL,'t',121,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('feane','menu','menu.item.{i}.name','Menyrätt – namn','text',NULL,NULL,NULL,NULL,'t',122,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('feane','menu','menu.item.{i}.price','Menyrätt – pris','text',NULL,NULL,NULL,NULL,'t',123,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('feane','gallery','gallery.heading','Galleri – rubrik','text',NULL,NULL,NULL,NULL,'f',250,'text','Galleri',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('feane','gallery','gallery.image.{i}','Galleribild','asset','image','4:5',NULL,NULL,'t',251,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('feane','testimonials','testimonials.heading','Omdömen – rubrik','text',NULL,NULL,NULL,NULL,'f',300,'text','Vad våra kunder säger',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('feane','contact','contact.heading','Kontakt – rubrik','text',NULL,NULL,NULL,NULL,'f',400,'text','Kontakt',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('feane','contact','contact.address','Kontakt – adress/text','text',NULL,NULL,NULL,NULL,'f',401,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('feane','contact','contact.map','Kontakt – karta/bild','asset','image','16:9',NULL,NULL,'f',402,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('feane','footer','footer.logo','Sidfot – logotyp','asset','logo',NULL,NULL,NULL,'f',500,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('feane','footer','footer.text','Sidfot – text','text',NULL,NULL,NULL,NULL,'f',501,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('haircut','hero','hero.bg','Hero – bakgrundsbild','asset','image','16:9',NULL,NULL,'f',0,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('haircut','hero','hero.heading','Hero – rubrik','text',NULL,NULL,NULL,NULL,'f',1,'text','Välkommen',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('haircut','hero','hero.subheading','Hero – underrubrik','text',NULL,NULL,NULL,NULL,'f',2,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('haircut','services','services.heading','Tjänster – rubrik','text',NULL,NULL,NULL,NULL,'f',100,'text','Våra tjänster',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('haircut','services','services.list','Tjänster – tjänstelista (boknings-modul)','module',NULL,NULL,'booking','service_list','f',101,NULL,NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('haircut','team','team.heading','Team – rubrik','text',NULL,NULL,NULL,NULL,'f',200,'text','Vårt team',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('haircut','team','team.member.{i}.photo','Medarbetare – bild','asset','image','1:1',NULL,NULL,'t',201,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('haircut','team','team.member.{i}.name','Medarbetare – namn','text',NULL,NULL,NULL,NULL,'t',202,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('haircut','team','team.member.{i}.role','Medarbetare – titel','text',NULL,NULL,NULL,NULL,'t',203,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('haircut','testimonials','testimonials.heading','Omdömen – rubrik','text',NULL,NULL,NULL,NULL,'f',300,'text','Vad våra kunder säger',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('haircut','footer','footer.logo','Sidfot – logotyp','asset','logo',NULL,NULL,NULL,'f',500,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('haircut','footer','footer.text','Sidfot – text','text',NULL,NULL,NULL,NULL,'f',501,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('restoran','hero','hero.bg','Hero – bakgrundsbild','asset','image','16:9',NULL,NULL,'f',0,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('restoran','hero','hero.heading','Hero – rubrik','text',NULL,NULL,NULL,NULL,'f',1,'text','Välkommen',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('restoran','hero','hero.subheading','Hero – underrubrik','text',NULL,NULL,NULL,NULL,'f',2,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('restoran','menu','menu.heading','Meny – rubrik','text',NULL,NULL,NULL,NULL,'f',120,'text','Meny',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('restoran','menu','menu.item.{i}.image','Menyrätt – bild','asset','image','1:1',NULL,NULL,'t',121,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('restoran','menu','menu.item.{i}.name','Menyrätt – namn','text',NULL,NULL,NULL,NULL,'t',122,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('restoran','menu','menu.item.{i}.price','Menyrätt – pris','text',NULL,NULL,NULL,NULL,'t',123,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('restoran','gallery','gallery.heading','Galleri – rubrik','text',NULL,NULL,NULL,NULL,'f',250,'text','Galleri',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('restoran','gallery','gallery.image.{i}','Galleribild','asset','image','4:5',NULL,NULL,'t',251,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('restoran','testimonials','testimonials.heading','Omdömen – rubrik','text',NULL,NULL,NULL,NULL,'f',300,'text','Vad våra kunder säger',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('restoran','contact','contact.heading','Kontakt – rubrik','text',NULL,NULL,NULL,NULL,'f',400,'text','Kontakt',NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('restoran','contact','contact.address','Kontakt – adress/text','text',NULL,NULL,NULL,NULL,'f',401,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('restoran','contact','contact.map','Kontakt – karta/bild','asset','image','16:9',NULL,NULL,'f',402,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('restoran','footer','footer.logo','Sidfot – logotyp','asset','logo',NULL,NULL,NULL,'f',500,'asset',NULL,NULL) on conflict (template_key,slot_key) do nothing;
insert into template_slots (template_key,section_key,slot_key,label,kind,asset_role,aspect_hint,module_key,module_view,repeatable,sort_order,default_kind,default_text,default_asset_key) values ('restoran','footer','footer.text','Sidfot – text','text',NULL,NULL,NULL,NULL,'f',501,'text',NULL,NULL) on conflict (template_key,slot_key) do nothing;

-- ===== restore the one tenant look-pin purged by 0045 (test234rf) =====
update tenant_settings set settings = jsonb_set(settings, '{look}', '"haircare"')
where tenant_id = '5163112c-afd3-4a0b-8f4c-9aef3ce2bb96';

commit;
