packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - electron
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

ignoredBuiltDependencies:
  - electron-winstaller

patchedDependencies:
  '@opennextjs/cloudflare@1.19.11': patches/@opennextjs__cloudflare@1.19.11.patch
