/* Corevo Storefront — demo tenant data + shared photography manifest.
   Photos are Unsplash placeholders standing in for tenant uploads. */

// High-quality Unsplash placeholders (salon / hair / barber).
const IMG = {
  // editorial salon interiors & action
  salonInterior:  "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=1600&q=80&auto=format&fit=crop",
  salonChairs:    "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1600&q=80&auto=format&fit=crop",
  styling:        "https://images.unsplash.com/photo-1633681926035-ec1ac984418a?w=1600&q=80&auto=format&fit=crop",
  cutting:        "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=1600&q=80&auto=format&fit=crop",
  washing:        "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=1600&q=80&auto=format&fit=crop",
  color:          "https://images.unsplash.com/photo-1522336572468-97b06e8ef143?w=1600&q=80&auto=format&fit=crop",
  // barber world
  barberShop:     "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=1600&q=80&auto=format&fit=crop",
  barberCut:      "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=1600&q=80&auto=format&fit=crop",
  barberTools:    "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=1600&q=80&auto=format&fit=crop",
  beard:          "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=1600&q=80&auto=format&fit=crop",
  // portraits (stylists)
  p1: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&q=80&auto=format&fit=crop",
  p2: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80&auto=format&fit=crop",
  p3: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600&q=80&auto=format&fit=crop",
  p4: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80&auto=format&fit=crop",
  p5: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600&q=80&auto=format&fit=crop",
  p6: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&q=80&auto=format&fit=crop",
  // gallery / inspiration
  g1: "https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800&q=80&auto=format&fit=crop",
  g2: "https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?w=800&q=80&auto=format&fit=crop",
  g3: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=800&q=80&auto=format&fit=crop",
  g4: "https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80&auto=format&fit=crop",
  g5: "https://images.unsplash.com/photo-1562004760-acb5df9d8d2a?w=800&q=80&auto=format&fit=crop",
  g6: "https://images.unsplash.com/photo-1457972729786-0411a3b2b626?w=800&q=80&auto=format&fit=crop",
};

// The three demo tenants — one per template, proving distinct identities.
const TENANTS = {
  salvia: {
    theme: "salvia",
    name: "Studio Salvia",
    wordmark: "Studio Salvia",
    logoStyle: "serif",
    city: "Linköping",
    tagline: "Hårvård med lugn hand",
    heroEyebrow: "— Frisörsalong i Linköping",
    heroTitle: "Skarpt klippt.\nSkönt mottagen.",
    heroLede: "En stilla salong på Storgatan där varje klippning får ta sin tid. Boka en stund som är helt din.",
    heroImages: [IMG.salonInterior, IMG.styling, IMG.salonChairs],
    aboutCopy: "Salvia föddes ur en enkel idé: att ett frisörbesök ska kännas som en paus, inte ett ärende. Vi är ett litet team som bryr oss om hantverket och om dig som sitter i stolen.",
    aboutImage: IMG.washing,
    italic: "Varje stol är en stund för sig själv.",
    stats: [["8+", "år på Storgatan"], ["5,0★", "snittbetyg"], ["100%", "hantverk"]],
    services: [
      { n: "01", name: "Klippning dam", desc: "Konsultation, tvätt, klippning och styling.", time: "60 min", price: "695 kr" },
      { n: "02", name: "Klippning herr", desc: "Klassisk eller modern, tvätt och styling.", time: "45 min", price: "545 kr" },
      { n: "03", name: "Färg & slingor", desc: "Helfärg eller slingor med ton och vård.", time: "120 min", price: "fr. 1 450 kr" },
      { n: "04", name: "Styling & uppsättning", desc: "Inför fest, bröllop eller fotografering.", time: "60 min", price: "850 kr" },
      { n: "05", name: "Barn (t.o.m. 12 år)", desc: "Lugn klippning i egen takt.", time: "30 min", price: "345 kr" },
    ],
    team: [
      { name: "Elin Sandberg", role: "Salongschef · Färgspecialist", img: IMG.p1 },
      { name: "Johanna Vik", role: "Frisör · Stylist", img: IMG.p3 },
      { name: "Maja Lund", role: "Frisör", img: IMG.p5 },
    ],
    gallery: [IMG.g1, IMG.g2, IMG.g3, IMG.g4, IMG.g5, IMG.g6],
    address: "Storgatan 22, 582 23 Linköping",
    hours: [["Mån–Tor", "09–18"], ["Fre", "09–17"], ["Lör", "10–14"], ["Sön", "Stängt"]],
    instagram: "@studiosalvia",
  },
  leander: {
    theme: "leander",
    name: "Maison Leander",
    wordmark: "Maison Leander",
    logoStyle: "serif",
    city: "Linköping",
    tagline: "Din frisör i Linköping",
    heroEyebrow: "— Salong & färgateljé",
    heroTitle: "Din frisör\ni Linköping",
    heroLede: "Välkommen till Maison Leander — en varm ateljé för färg, klipp och omsorg. Vi tar emot dig som en gäst, inte ett bokningsnummer.",
    heroImages: [IMG.styling, IMG.color, IMG.salonInterior],
    aboutCopy: "Hos oss möts hantverk och värme. Vi arbetar med skandinaviska färgtekniker och en lugn, personlig ton — för att du ska gå härifrån som mest lik dig själv.",
    aboutImage: IMG.color,
    italic: "Vacker hårfärg börjar med ett samtal.",
    stats: [["12", "år i staden"], ["4,9★", "av 600+ omdömen"], ["6", "frisörer"]],
    services: [
      { n: "01", name: "Klipp & form", desc: "Konsultation, klipp och styling efter ditt hår.", time: "60 min", price: "750 kr" },
      { n: "02", name: "Balayage", desc: "Mjuka, handmålade slingor med ton.", time: "150 min", price: "fr. 1 950 kr" },
      { n: "03", name: "Helfärg", desc: "Jämn, blank färg med vårdande omtanke.", time: "120 min", price: "fr. 1 350 kr" },
      { n: "04", name: "Bröllop & fest", desc: "Provuppsättning och styling för dagen.", time: "90 min", price: "1 250 kr" },
      { n: "05", name: "Klippning herr", desc: "Klipp, tvätt och styling.", time: "45 min", price: "595 kr" },
    ],
    team: [
      { name: "Sofia Leander", role: "Grundare · Coloriste", img: IMG.p2 },
      { name: "Amanda Krook", role: "Senior frisör", img: IMG.p4 },
      { name: "Nora Berg", role: "Frisör · Balayage", img: IMG.p1 },
    ],
    gallery: [IMG.g4, IMG.g5, IMG.g2, IMG.g6, IMG.g1, IMG.g3],
    address: "Ågatan 41, 582 22 Linköping",
    hours: [["Mån–Fre", "09–19"], ["Lör", "10–16"], ["Sön", "Stängt"], ["", ""]],
    instagram: "@maisonleander",
  },
  zigge: {
    theme: "zigge",
    name: "Zigge",
    wordmark: "ZIGGE",
    logoStyle: "display",
    city: "Linköping",
    tagline: "Frisör & barberare",
    heroEyebrow: "— Frisör & barberare · est. 2014",
    heroTitle: "RENT SNITT.\nINGEN KRÅNGEL.",
    heroLede: "Klippning och skäggvård för alla. Drop in eller boka online — du sitter i stolen samma dag.",
    heroImages: [IMG.barberShop, IMG.barberCut, IMG.barberTools],
    aboutCopy: "Zigge är hörnsalongen där frisör möter barberare. Vi håller det enkelt, vasst och prisvärt — och vi minns hur du gillar din fade.",
    aboutImage: IMG.barberTools,
    italic: "Av frisörer, för alla.",
    stats: [["10", "år i kvarteret"], ["18k", "klippningar"], ["Drop-in", "varje dag"]],
    services: [
      { n: "01", name: "Herrklippning", desc: "Maskin & sax, tvätt och styling.", time: "30 min", price: "395 kr" },
      { n: "02", name: "Skägg & trim", desc: "Rakkniv, form och olja.", time: "30 min", price: "295 kr" },
      { n: "03", name: "Klipp + skägg", desc: "Hela paketet i ett besök.", time: "45 min", price: "595 kr" },
      { n: "04", name: "Fade / skin fade", desc: "Skarp övergång, precision.", time: "45 min", price: "445 kr" },
      { n: "05", name: "Damklippning", desc: "Klipp, tvätt och föning.", time: "45 min", price: "545 kr" },
    ],
    team: [
      { name: "Ziggy Demir", role: "Grundare · Barberare", img: IMG.p6 },
      { name: "Leo Nyström", role: "Barberare", img: IMG.p4 },
      { name: "Karim Aziz", role: "Frisör · Fade-specialist", img: IMG.p2 },
    ],
    gallery: [IMG.barberCut, IMG.beard, IMG.barberShop, IMG.barberTools, IMG.g6, IMG.cutting],
    address: "Nygatan 9, 582 19 Linköping",
    hours: [["Mån–Fre", "10–19"], ["Lör", "10–16"], ["Sön", "12–16"], ["Drop-in", "alltid"]],
    instagram: "@ziggefrisor",
  },
  linnea: {
    theme: "linnea",
    name: "Salong Linnea",
    wordmark: "Linnea",
    logoStyle: "serif",
    city: "Linköping",
    tagline: "Naturlig hårvård i Linköping",
    heroEyebrow: "— Frisör & färgsalong",
    heroTitle: "Naturligt vacker,\nhelt enkelt.",
    heroLede: "En varm salong med fokus på friskt hår och naturliga toner. Välkommen in för en stund av omtanke.",
    heroImages: [IMG.washing, IMG.salonInterior, IMG.styling],
    aboutCopy: "Linnea är salongen för dig som vill vårda ditt hår på riktigt. Vi arbetar med skonsamma produkter och naturliga färger — och tar oss alltid tid.",
    aboutImage: IMG.washing,
    italic: "Det vackraste håret är friskt hår.",
    stats: [["9", "år i Linköping"], ["4,9★", "snittbetyg"], ["Eko", "produkter"]],
    services: [
      { n: "01", name: "Klipp & vård", desc: "Konsultation, klipp och inpackning.", time: "60 min", price: "650 kr" },
      { n: "02", name: "Naturlig färg", desc: "Skonsam färg med vegetabiliska toner.", time: "120 min", price: "fr. 1 350 kr" },
      { n: "03", name: "Slingor", desc: "Mjuka, ljusa slingor med ton.", time: "150 min", price: "fr. 1 650 kr" },
      { n: "04", name: "Hårbottenbehandling", desc: "Lugnande behandling för hårbotten.", time: "45 min", price: "550 kr" },
      { n: "05", name: "Barn (t.o.m. 12 år)", desc: "Lugn klippning i egen takt.", time: "30 min", price: "325 kr" },
    ],
    team: [
      { name: "Linnea Ahl", role: "Grundare · Färg", img: IMG.p5 },
      { name: "Klara Ström", role: "Frisör", img: IMG.p1 },
      { name: "Tove Ek", role: "Frisör · Vård", img: IMG.p3 },
    ],
    gallery: [IMG.g3, IMG.g1, IMG.g5, IMG.g2, IMG.g4, IMG.g6],
    address: "Trädgårdsgatan 7, 582 25 Linköping",
    hours: [["Mån–Tor", "09–18"], ["Fre", "09–16"], ["Lör", "10–14"], ["Sön", "Stängt"]],
    instagram: "@salonglinnea",
  },
  edit: {
    theme: "edit",
    name: "Edit Hår",
    wordmark: "Edit",
    logoStyle: "serif",
    city: "Linköping",
    tagline: "Klipp & färg, redaktionellt",
    heroEyebrow: "— Hårstudio i Linköping",
    heroTitle: "Form, färg\noch finess.",
    heroLede: "En redaktionell hårstudio för precisa klipp och raffinerad färg. Boka en tid i lugn och ro.",
    heroImages: [IMG.cutting, IMG.color, IMG.salonChairs],
    aboutCopy: "Edit är studion för dig som vill ha ett genomtänkt klipp. Vi ser på hår som form — rent, modernt och personligt, varje gång.",
    aboutImage: IMG.cutting,
    italic: "Ett klipp är arkitektur för håret.",
    stats: [["7", "år"], ["5,0★", "snittbetyg"], ["2", "studior"]],
    services: [
      { n: "01", name: "Precisionsklipp dam", desc: "Konsultation, klipp och styling.", time: "60 min", price: "795 kr" },
      { n: "02", name: "Precisionsklipp herr", desc: "Skarpt klipp, tvätt och styling.", time: "45 min", price: "595 kr" },
      { n: "03", name: "Färg & ton", desc: "Helfärg eller toning med glans.", time: "120 min", price: "fr. 1 450 kr" },
      { n: "04", name: "Klippning & färg", desc: "Det kompletta besöket.", time: "150 min", price: "fr. 1 950 kr" },
      { n: "05", name: "Fön & styling", desc: "Inför event eller foto.", time: "40 min", price: "450 kr" },
    ],
    team: [
      { name: "Edvin Roos", role: "Grundare · Stylist", img: IMG.p2 },
      { name: "Hanna Falk", role: "Senior frisör", img: IMG.p1 },
      { name: "Iris Berg", role: "Coloriste", img: IMG.p3 },
    ],
    gallery: [IMG.g2, IMG.g4, IMG.g1, IMG.g3, IMG.g6, IMG.g5],
    address: "Repslagaregatan 19, 582 22 Linköping",
    hours: [["Mån–Fre", "10–19"], ["Lör", "10–15"], ["Sön", "Stängt"], ["", ""]],
    instagram: "@edithar",
  },
};

window.IMG = IMG;
window.TENANTS = TENANTS;
